const SAMPLE_PROJECT = {
  id: '11111111-1111-1111-1111-111111111111',
  title: 'Featured Project',
  description: 'Full description of featured project',
  short_description: 'Short desc',
  project_type: 'fixed',
  budget_min: 500,
  budget_max: 2000,
  budget_currency: 'USD',
  // provide a combined `budget` field expected by contract tests
  budget: { min: 500, max: 2000, currency: 'USD' },
  featured: true
}

async function getProjectDetail(id) {
  if (!id) return null
  if (id === SAMPLE_PROJECT.id) return SAMPLE_PROJECT
  return { id, title: 'Project ' + id, description: 'Autogenerated description', budget: { min: null, max: null, currency: 'USD' } }
}

module.exports = { getProjectDetail }
