const db = require('../db')
const SAMPLE_DEVS = require('./publicDevelopersController').SAMPLE_DEVS || []

async function getDeveloperDetail(id, opts = {}) {
  if (!id) return null
  if (db.pool) {
    const { rows } = await db.query('SELECT * FROM developer_profiles WHERE id = $1 AND is_public = true', [id])
    const dev = rows[0]
    if (!dev) return null
    if (opts && opts.authenticated) {
      // In real app, fetch contact info from users table or profiles
      dev.contact = { email: 'dev@example.com' }
    }
    // Ensure a stable public shape: include `name` alias for display_name
    if (!dev.name && dev.display_name) dev.name = dev.display_name
    return dev
  }
  const dev = SAMPLE_DEVS.find(d => d.id === id) || { id, display_name: 'Dev ' + id, summary: 'Autogenerated summary' }
  if (opts && opts.authenticated) return { ...dev, contact: { email: 'dev@example.com' } }
  // Ensure `name` exists for sample devs as well
  if (!dev.name && dev.display_name) dev.name = dev.display_name
  // Ensure skills array exists for contract shape
  if (!dev.skills) dev.skills = []
  return dev
}

module.exports = { getDeveloperDetail }
