name: CI

on:
  push:
    branches: [ main, 003-title-client-dashboard ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install repository dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint (frontend)
        working-directory: frontend
        run: pnpm dlx eslint "src/**/*.{ts,tsx,js,jsx}" --max-warnings 0

      - name: Run frontend Vitest (contracts + integration)
        working-directory: frontend
        run: pnpm vitest --run
        env:
          CI: true
