openapi: 3.0.3
info:
  title: WorkDev Core API (partial)
  version: 0.1.0
paths:
  /auth/register:
    post:
      summary: Register with email/password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Registration initiated (email verification sent)

  /auth/oauth/callback:
    post:
      summary: OAuth callback for GitHub/Google
      responses:
        '200':
          description: OAuth login successful

  /profiles/{id}:
    get:
      summary: Get public profile
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Public profile data

  /messages:
    post:
      summary: Send a message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: string
                recipient_id:
                  type: string
                body:
                  type: string
      responses:
        '201':
          description: Message created

  /projects/{id}/reviews:
    post:
      summary: Submit a review for a project
      parameters:
        - in: path
          name: id
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quality:
                  type: integer
                communication:
                  type: integer
                expertise:
                  type: integer
                deadlines:
                  type: integer
                comment:
                  type: string
      responses:
        '201':
          description: Review created
